services:
  postgres:
    image: postgres:latest
    container_name: Scola-Postgres
    env_file:
      - ./.env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init-docker.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrator:
    image: nxyt/sqlx-cli:latest
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgres://${BACKEND_DATABASE_USER}:${BACKEND_DATABASE_PASSWORD}@postgres:5432/${BACKEND_DATABASE_NAME}
    command: sqlx database setup
    volumes:
      - ./backend/migrations:/migrations
    networks:
      - postgres

  valkey:
    image: valkey/valkey:latest
    container_name: Scola-Valkey
    env_file:
      - ./.env
    ports:
      - "${VALKEY_PORT}:6379"
    volumes:
      - valkey_data:/data
    environment:
      # save all 60s, if at least 1 key was changed
      # create the specified user and the specified password
      VALKEY_EXTRA_FLAGS: >-
        --save 60 1 
        --user ${BACKEND_VALKEY_USER} on >${BACKEND_VALKEY_PASSWORD} db=${BACKEND_VALKEY_DATABASE} allkeys nocommands +get +setex +del +scan
    networks:
      - valkey
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  backend:
    depends_on:
      postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
      valkey:
        condition: service_healthy
    container_name: Scola-Backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgres://${BACKEND_DATABASE_USER}:${BACKEND_DATABASE_PASSWORD}@postgres:5432/${BACKEND_DATABASE_NAME}
      REDIS_URL: valkey://${BACKEND_VALKEY_USER}:${BACKEND_VALKEY_PASSWORD}@valkey:6379/${BACKEND_VALKEY_DATABASE}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - postgres
      - valkey

volumes:
  postgres_data:
  valkey_data:

networks:
  postgres:
  valkey: