services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - ./.env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init-docker.sh:/docker-entrypoint-initdb.d/init.sh
    networks:
      - database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrator:
    image: nxyt/sqlx-cli:latest
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgres://${BACKEND_DATABASE_USER}:${BACKEND_DATABASE_PASSWORD}@postgres:5432/${BACKEND_DATABASE_NAME}
    command: sqlx database setup
    volumes:
      - ./backend/migrations:/migrations
    networks:
      - database

  backend:
    depends_on:
      postgres:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./backend/Dockerfile
    env_file:
      - ./.env
    environment:
      DATABASE_URL: postgres://${BACKEND_DATABASE_USER}:${BACKEND_DATABASE_PASSWORD}@postgres:5432/${BACKEND_DATABASE_NAME}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - database

volumes:
  postgres_data:

networks:
  database: