#/bin/sh
psql -v ON_ERROR_STOP=1 <<-EOSQL
    CREATE ROLE $BACKEND_DATABASE_USER WITH
        LOGIN
		NOSUPERUSER 
		CREATEDB 
		NOCREATEROLE
        NOINHERIT 
		NOREPLICATION 
		NOBYPASSRLS
        CONNECTION LIMIT -1
        PASSWORD '$BACKEND_DATABASE_PASSWORD';
EOSQL