CREATE TABLE IF NOT EXISTS class (
	id UUID PRIMARY KEY NOT NULL,
	school_id UUID NOT NULL, FOREIGN KEY(school_id) REFERENCES school(id) ON DELETE CASCADE,
	teacher_id UUID NOT NULL, FOREIGN KEY(teacher_id) REFERENCES teacher(id) ON DELETE CASCADE,
	name VARCHAR(100) NOT NULL,
	abbreviation VARCHAR(100) NOT NULL,
	description VARCHAR(100) NOT NULL
);