CREATE TABLE IF NOT EXISTS lesson (
	id UUID PRIMARY KEY NOT NULL,
	course_id UUID NOT NULL, FOREIGN KEY(course_id) REFERENCES course(id) ON DELETE CASCADE, 
	room_id UUID NOT NULL, FOREIGN KEY(room_id) REFERENCES room(id) ON DELETE CASCADE, 
	start_time TIMETZ NOT NULL,
	end_time TIMETZ NOT NULL,
	title VARCHAR(100) NOT NULL
);