TRUNCATE TABLE "lessonOverride" CASCADE;

TRUNCATE TABLE absence CASCADE;

TRUNCATE TABLE grade CASCADE;

TRUNCATE TABLE lesson CASCADE;

TRUNCATE TABLE "classToCourse";

TRUNCATE TABLE semester CASCADE;

TRUNCATE TABLE course CASCADE;

TRUNCATE TABLE student CASCADE;

TRUNCATE TABLE class CASCADE;

TRUNCATE TABLE teacher CASCADE;

TRUNCATE TABLE person CASCADE;

TRUNCATE TABLE room CASCADE;

TRUNCATE TABLE school CASCADE;