### LOGIN
POST {{BASE}}/auth/login
Content-Type: application/json

{
	"school": "2c64f5d3-4c82-4474-acf6-caa82be28f66",
	"login_name": "patrick.lustenberger",
	"password": "1234"
}


### ME
GET {{BASE}}/auth/me
Accept: application/json

### LOGOUT
POST {{BASE}}/auth/logout
Accept: application/json