CREATE TABLE IF NOT EXISTS room (
	id UUID PRIMARY KEY NOT NULL,
	school_id UUID NOT NULL, FOREIGN KEY(school_id) REFERENCES school(id) ON DELETE CASCADE,
	name VARCHAR(100) NOT NULL,
	description VARCHAR(100) NOT NULL,
	building VARCHAR(100) NOT NULL
);