CREATE TABLE IF NOT EXISTS semester (
	id UUID PRIMARY KEY NOT NULL,
	school_id UUID NOT NULL, FOREIGN KEY(school_id) REFERENCES school(id) ON DELETE CASCADE,
	name VARCHAR(100) NOT NULL,
	start_date DATE NOT NULL,
	end_date DATE NOT NULL
);